// SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
// SPDX-License-Identifier: Apache-2.0

package main

var Sensors = []Sensor{
	// Modbus registers from LG PCS (Power Conditioning Unit)
	// Mapping is unknown. Probably internal to LG
	{
		Quantity:          Quantity{0x9c84, 2, 1, 0, nil},
		Name:              "Active Power AC",
		UnitOfMeasurement: "W",
		FriendlyName:      "",
		DeviceClass:       DeviceClassPower,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9c88, 2, 1, 0, nil},
		Name:              "Status PV-C1",
		UnitOfMeasurement: "",
		FriendlyName:      "",
		DeviceClass:       "",
		StateClass:        "",
		Icon:              "",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9c8A, 2, 1, 0, nil},
		Name:              "Voltage PV-C1",
		UnitOfMeasurement: "V",
		FriendlyName:      "",
		DeviceClass:       DeviceClassVoltage,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9c92, 2, 0.96, 0, nil},
		Name:              "Active Power DC PV-C1",
		UnitOfMeasurement: "W",
		FriendlyName:      "",
		DeviceClass:       DeviceClassPower,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9c94, 2, 1, 0, nil},
		Name:              "Status PV-C2",
		UnitOfMeasurement: "",
		FriendlyName:      "",
		DeviceClass:       "",
		StateClass:        "",
		Icon:              "",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9c96, 2, 1, 0, nil},
		Name:              "Voltage PV-C2",
		UnitOfMeasurement: "V",
		FriendlyName:      "",
		DeviceClass:       DeviceClassVoltage,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9c98, 2, 0.96, 0, nil},
		Name:              "Active Power DC PV-C2",
		UnitOfMeasurement: "W",
		FriendlyName:      "",
		DeviceClass:       DeviceClassPower,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cA2, 2, 1, 0, nil},
		Name:              "Energy 3?",
		UnitOfMeasurement: "kWh?",
		FriendlyName:      "",
		DeviceClass:       DeviceClassEnergy,
		StateClass:        StateClassTotalIncreasing,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cA4, 2, 1e-2, 0, nil},
		Name:              "Frequency",
		UnitOfMeasurement: "Hz",
		FriendlyName:      "",
		DeviceClass:       DeviceClassFrequency,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:sine-wave",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cA6, 2, 1, 0, nil},
		Name:              "Voltage Batt1?",
		UnitOfMeasurement: "V",
		FriendlyName:      "",
		DeviceClass:       DeviceClassVoltage,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cA8, 2, 1, 0, nil},
		Name:              "Discharge-Charge Batt?",
		UnitOfMeasurement: "W?",
		FriendlyName:      "",
		DeviceClass:       DeviceClassPower,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cAA, 2, 1, 0, nil},
		Name:              "Charge-Discharge Batt?",
		UnitOfMeasurement: "W?",
		FriendlyName:      "",
		DeviceClass:       DeviceClassPower,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cAA, 2, 1, 0, nil},
		Name:              "Active Power Batt?",
		UnitOfMeasurement: "W?",
		FriendlyName:      "",
		DeviceClass:       DeviceClassPower,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cB6, 2, 1, 0, nil},
		Name:              "Status?",
		UnitOfMeasurement: "",
		FriendlyName:      "",
		DeviceClass:       "",
		StateClass:        "",
		Icon:              "",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cB8, 2, 1, 0, nil},
		Name:              "Voltage Batt2?",
		UnitOfMeasurement: "V",
		FriendlyName:      "",
		DeviceClass:       DeviceClassVoltage,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cBA, 2, 1, 0, nil},
		Name:              "Discharge-charge",
		UnitOfMeasurement: "?",
		FriendlyName:      "",
		DeviceClass:       "",
		StateClass:        "",
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cC4, 2, 100.0 / 905, -45, nil},
		Name:              "Current SoC",
		UnitOfMeasurement: "%",
		FriendlyName:      "",
		DeviceClass:       DeviceClassBattery,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:battery",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cC6, 2, 100.0 / 905, -45, nil},
		Name:              "Max SoC",
		UnitOfMeasurement: "%",
		FriendlyName:      "",
		DeviceClass:       DeviceClassBattery,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:battery",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cD2, 2, 1, 0, nil},
		Name:              "Energy 1",
		UnitOfMeasurement: "kWh?",
		FriendlyName:      "",
		DeviceClass:       DeviceClassEnergy,
		StateClass:        StateClassTotalIncreasing,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},
	{
		Quantity:          Quantity{0x9cD4, 2, 1, 0, nil},
		Name:              "Energy 2",
		UnitOfMeasurement: "kWh?",
		FriendlyName:      "",
		DeviceClass:       DeviceClassEnergy,
		StateClass:        StateClassTotalIncreasing,
		Icon:              "mdi:lightning-bolt",
		Source:            "pcs",
	},

	// Modbus registers from ABB EQ-B Energy Meters
	// See: https://library.abb.com/d/2CDC512084D0101
	{
		Quantity:          Quantity{0x5000, 4, 1e-2, 0, nil},
		Name:              "Active import",
		UnitOfMeasurement: "kWh",
		FriendlyName:      "",
		DeviceClass:       DeviceClassEnergy,
		StateClass:        StateClassTotalIncreasing,
		Icon:              "mdi:transmission-tower-import",
		Source:            "pm",
	},
	{
		Quantity:          Quantity{0x5004, 4, 1e-2, 0, nil},
		Name:              "Active export",
		UnitOfMeasurement: "kWh",
		FriendlyName:      "",
		DeviceClass:       DeviceClassEnergy,
		StateClass:        StateClassTotalIncreasing,
		Icon:              "mdi:transmission-tower-export",
		Source:            "pm",
	},
	{
		Quantity:          Quantity{0x5b00, 2, 1e-1, 0, nil},
		Name:              "Voltage L1-N",
		UnitOfMeasurement: "V",
		FriendlyName:      "",
		DeviceClass:       DeviceClassVoltage,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pm",
	},
	{
		Quantity:          Quantity{0x5b02, 2, 1e-1, 0, nil},
		Name:              "Voltage L2-N",
		UnitOfMeasurement: "V",
		FriendlyName:      "",
		DeviceClass:       DeviceClassVoltage,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pm",
	},
	{
		Quantity:          Quantity{0x5b04, 2, 1e-1, 0, nil},
		Name:              "Voltage L3-N",
		UnitOfMeasurement: "V",
		FriendlyName:      "",
		DeviceClass:       DeviceClassVoltage,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pm",
	},
	{
		Quantity:          Quantity{0x5b14, 2, 1e-3, 0, nil},
		Name:              "Active power Total",
		UnitOfMeasurement: "W",
		FriendlyName:      "",
		DeviceClass:       DeviceClassPower,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:lightning-bolt",
		Source:            "pm",
	},
	{
		Quantity:          Quantity{0x5b2c, 1, 1e-2, 0, nil},
		Name:              "Frequency",
		UnitOfMeasurement: "Hz",
		FriendlyName:      "",
		DeviceClass:       DeviceClassFrequency,
		StateClass:        StateClassMeasurement,
		Icon:              "mdi:sine-wave",
		Source:            "pm",
	},
}
